"""add_parent_id_to_students

Revision ID: cb7761ef43a3
Revises: 1b44011cf362
Create Date: 2026-05-04 09:17:58.759669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cb7761ef43a3'
down_revision: Union[str, None] = '1b44011cf362'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('parent_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_students_parent_id'), 'students', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'students', 'users', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_index(op.f('ix_students_parent_id'), table_name='students')
    op.drop_column('students', 'parent_id')
    # ### end Alembic commands ###
