"""add_exams_grades

Revision ID: fd5fe20f1357
Revises: cb7761ef43a3
Create Date: 2026-05-04 03:57:15.906141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fd5fe20f1357'
down_revision: Union[str, None] = 'cb7761ef43a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('max_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight_percent', sa.SmallInteger(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('quiz', 'midterm', 'final', 'assignment')", name='ck_exam_type'),
    sa.CheckConstraint('weight_percent BETWEEN 0 AND 100', name='ck_exam_weight'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_class_id'), 'exams', ['class_id'], unique=False)
    op.create_index(op.f('ix_exams_organization_id'), 'exams', ['organization_id'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('graded_by', sa.UUID(), nullable=False),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['graded_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'student_id', name='uq_grade')
    )
    op.create_index(op.f('ix_grades_exam_id'), 'grades', ['exam_id'], unique=False)
    op.create_index(op.f('ix_grades_student_id'), 'grades', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grades_student_id'), table_name='grades')
    op.drop_index(op.f('ix_grades_exam_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_exams_organization_id'), table_name='exams')
    op.drop_index(op.f('ix_exams_class_id'), table_name='exams')
    op.drop_table('exams')
    # ### end Alembic commands ###
